name: ci

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda and dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7
          activate-environment: coastalvegedge-detection-scivision
          environment-file: environment.yml
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install pytest
          pytest -s ./tests/test_workflow.py